//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D HDRSampler;
//   float4 TexelSize;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   TexelSize    c66      1
//   HDRSampler   s0       1
//

    ps_3_0
    def c0, -3, 0, 0.699999988, -2
    def c1, 0.800000012, -1, 0, 0.899999976
    def c2, 0.172413796, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    mov r0.xyw, c0
    mad r1.xy, c66, r0, v0
    texld r1, r1, s0
    texld r2, v0, s0
    add r1.xyz, r1, -r2
    mul r3.xyz, r1, c0.z
    cmp r1.xyz, r1, r3, c0.y
    mad r3.xy, c66, r0.wyzw, v0
    texld r3, r3, s0
    add r3.xyz, -r2, r3
    mul r4.xyz, r3, c1.x
    cmp r3.xyz, r3, r4, c0.y
    add r1.xyz, r1, r3
    mov r3.yz, c1
    mad r3.xw, c66.xyzy, r3.yyzz, v0.xyzy
    texld r4, r3.xwzw, s0
    add r4.xyz, -r2, r4
    mul r5.xyz, r4, c1.w
    cmp r4.xyz, r4, r5, c0.y
    add r1.xyz, r1, r4
    mad r3.xy, c66, r3_abs.yzzw, v0
    texld r3, r3, s0
    add r3.xyz, -r2, r3
    mul r4.xyz, r3, c1.w
    cmp r3.xyz, r3, r4, c0.y
    add r1.xyz, r1, r3
    mad r0.zw, c66.xyxy, r0_abs.xywy, v0.xyxy
    texld r3, r0.zwzw, s0
    add r3.xyz, -r2, r3
    mul r4.xyz, r3, c1.x
    cmp r3.xyz, r3, r4, c0.y
    add r1.xyz, r1, r3
    mad r0.xy, c66, r0_abs, v0
    texld r0, r0, s0
    add r0.xyz, -r2, r0
    mul r3.xyz, r0, c0.z
    cmp r0.xyz, r0, r3, c0.y
    add r0.xyz, r1, r0
    mad oC0.xyz, r0, c2.x, r2
    mov oC0.w, -c1.y

// approximately 40 instruction slots used (7 texture, 33 arithmetic)
